from Packetizer import *
from Depacketizer import *

value = b'\x01'*25
p = Packetizer(value, 10)
d = Depacketizer(p.PacketsRemaining(), p.FinalPacketSize(), 10)
print(p.PacketSize(), d.PacketSize())
print(p.FinalPacketSize(), d.FinalPacketSize())
print(p.PacketsRemaining(), d.PacketsRemaining())
print(p.OnFinalPacket(), d.OnFinalPacket())
print(p.Done(), d.Done())
data1 = p.Next()
d.Next(data1)
print(data1)
print(d.Data())
print(p.PacketsRemaining(), d.PacketsRemaining())
print(p.OnFinalPacket(), d.OnFinalPacket())
print(p.Done(), d.Done())
data2 = p.Next()
d.Next(data2)
print(data2)
print(d.Data())
print(p.PacketsRemaining(), d.PacketsRemaining())
print(p.OnFinalPacket(), d.OnFinalPacket())
print(p.Done(), d.Done())
data3 = p.Next()
d.Next(data3)
print(data3)
print(d.Data())
print(p.FinalPacketSize(), d.FinalPacketSize())
print(p.PacketsRemaining(), d.PacketsRemaining())
print(p.OnFinalPacket(), d.OnFinalPacket())
print(p.Done(), d.Done())

